---
abstract: 'couchdb command line utils'
author:
  - 'Maroun NAJM <mnajm@cinemoz.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CouchDB-Utils
requires:
  AnyEvent::CouchDB: 0
  App::Cmd::Setup: 0
  File::Basename: 0
  File::MimeInfo::Simple: 0
  File::Path: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  JSON: 0
  JSON::XS: 0
  MIME::Base64: 0
  URI: 0
  strict: 0
  utf8: 0
  warnings: 0
version: 0.1
